"""Which bytes of each ROM segment the spec regenerates (no ROM access).

    python -m games.hm64.coverage <segs.json> <spec dir>
Prints per segment group: size, regenerated bytes, uncovered bytes (kept structure or missed art).
"""
import json
import os
import sys
from collections import defaultdict

import numpy as np


def main():
    segs = json.load(open(sys.argv[1]))
    spec = json.load(open(os.path.join(sys.argv[2], "textures.json")))
    cov = np.zeros(0x1000000, bool)
    for t in spec["textures"]:
        cov[t["off"]:t["off"] + t["n"]] = True
    for p in spec["palettes"]:
        cov[p["off"]:p["off"] + 2 * p["n"]] = True
    f = spec["font"]
    cov[f["off"]:f["end"]] = True
    for p in f["palettes"]:
        cov[p["off"]:p["off"] + 32] = True
    g = defaultdict(lambda: [0, 0, 0])
    worst = []
    for s in segs:
        key = "/".join(s["dir"].split("/")[:2]) or s["name"]
        n = s["end"] - s["start"]
        c = int(cov[s["start"]:s["end"]].sum())
        g[key][0] += 1
        g[key][1] += n
        g[key][2] += c
        if n > 4096 and (key.startswith("assets") or key.startswith("maps")):
            worst.append((n - c, s["name"], n))
    for k, (cnt, n, c) in sorted(g.items(), key=lambda kv: -kv[1][1]):
        if n > 2048:
            print(f"{k:32s} {cnt:4d} segs {n / 1024:8.1f} KB  regen {c / 1024:8.1f} KB  rest {(n - c) / 1024:8.1f} KB")
    print("largest uncovered asset/map segments:")
    for u, name, n in sorted(worst, reverse=True)[:12]:
        print(f"  {name:40s} {u / 1024:7.1f} KB of {n / 1024:7.1f}")


if __name__ == "__main__":
    main()
